// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgCommon.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MsgCommon.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

void protobuf_ShutdownFile_MsgCommon_2eproto() {
  delete CMsgCommon::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_MsgCommon_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_MsgCommon_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  CMsgCommon::default_instance_ = new CMsgCommon();
  CMsgCommon::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MsgCommon_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_MsgCommon_2eproto_once_);
void protobuf_AddDesc_MsgCommon_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_MsgCommon_2eproto_once_,
                 &protobuf_AddDesc_MsgCommon_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MsgCommon_2eproto {
  StaticDescriptorInitializer_MsgCommon_2eproto() {
    protobuf_AddDesc_MsgCommon_2eproto();
  }
} static_descriptor_initializer_MsgCommon_2eproto_;
#endif
bool MSGCOMMON_ACTION_IsValid(int value) {
  switch(value) {
    case 0:
      return true;
    default:
      return false;
  }
}


namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int CMsgCommon::kNActionFieldNumber;
const int CMsgCommon::kIdRoleFieldNumber;
const int CMsgCommon::kNTypeFieldNumber;
const int CMsgCommon::kNDatasFieldNumber;
const int CMsgCommon::kN64DatasFieldNumber;
const int CMsgCommon::kStrDatasFieldNumber;
#endif  // !_MSC_VER

CMsgCommon::CMsgCommon()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CMsgCommon)
}

void CMsgCommon::InitAsDefaultInstance() {
}

CMsgCommon::CMsgCommon(const CMsgCommon& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CMsgCommon)
}

void CMsgCommon::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  naction_ = 0;
  idrole_ = GOOGLE_ULONGLONG(0);
  ntype_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CMsgCommon::~CMsgCommon() {
  // @@protoc_insertion_point(destructor:CMsgCommon)
  SharedDtor();
}

void CMsgCommon::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void CMsgCommon::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const CMsgCommon& CMsgCommon::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_MsgCommon_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_MsgCommon_2eproto();
#endif
  return *default_instance_;
}

CMsgCommon* CMsgCommon::default_instance_ = NULL;

CMsgCommon* CMsgCommon::New(::google::protobuf::Arena* arena) const {
  CMsgCommon* n = new CMsgCommon;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CMsgCommon::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<CMsgCommon*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  if (_has_bits_[0 / 32] & 7u) {
    ZR_(idrole_, ntype_);
    naction_ = 0;
  }

#undef ZR_HELPER_
#undef ZR_

  ndatas_.Clear();
  n64datas_.Clear();
  strdatas_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->clear();
}

bool CMsgCommon::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::StringOutputStream unknown_fields_string(
      mutable_unknown_fields());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string);
  // @@protoc_insertion_point(parse_start:CMsgCommon)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 nAction = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &naction_)));
          set_has_naction();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_idRole;
        break;
      }

      // optional uint64 idRole = 2;
      case 2: {
        if (tag == 16) {
         parse_idRole:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &idrole_)));
          set_has_idrole();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_nType;
        break;
      }

      // optional int64 nType = 3;
      case 3: {
        if (tag == 24) {
         parse_nType:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &ntype_)));
          set_has_ntype();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_nDatas;
        break;
      }

      // repeated int32 nDatas = 4;
      case 4: {
        if (tag == 32) {
         parse_nDatas:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 32, input, this->mutable_ndatas())));
        } else if (tag == 34) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_ndatas())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_nDatas;
        if (input->ExpectTag(40)) goto parse_n64Datas;
        break;
      }

      // repeated int64 n64Datas = 5;
      case 5: {
        if (tag == 40) {
         parse_n64Datas:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 1, 40, input, this->mutable_n64datas())));
        } else if (tag == 42) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, this->mutable_n64datas())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_n64Datas;
        if (input->ExpectTag(50)) goto parse_strDatas;
        break;
      }

      // repeated string strDatas = 6;
      case 6: {
        if (tag == 50) {
         parse_strDatas:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_strdatas()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_strDatas;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CMsgCommon)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CMsgCommon)
  return false;
#undef DO_
}

void CMsgCommon::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CMsgCommon)
  // required int32 nAction = 1;
  if (has_naction()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->naction(), output);
  }

  // optional uint64 idRole = 2;
  if (has_idrole()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->idrole(), output);
  }

  // optional int64 nType = 3;
  if (has_ntype()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->ntype(), output);
  }

  // repeated int32 nDatas = 4;
  for (int i = 0; i < this->ndatas_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      4, this->ndatas(i), output);
  }

  // repeated int64 n64Datas = 5;
  for (int i = 0; i < this->n64datas_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(
      5, this->n64datas(i), output);
  }

  // repeated string strDatas = 6;
  for (int i = 0; i < this->strdatas_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      6, this->strdatas(i), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   unknown_fields().size());
  // @@protoc_insertion_point(serialize_end:CMsgCommon)
}

int CMsgCommon::ByteSize() const {
  int total_size = 0;

  // required int32 nAction = 1;
  if (has_naction()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->naction());
  }
  if (_has_bits_[1 / 32] & 6u) {
    // optional uint64 idRole = 2;
    if (has_idrole()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->idrole());
    }

    // optional int64 nType = 3;
    if (has_ntype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->ntype());
    }

  }
  // repeated int32 nDatas = 4;
  {
    int data_size = 0;
    for (int i = 0; i < this->ndatas_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->ndatas(i));
    }
    total_size += 1 * this->ndatas_size() + data_size;
  }

  // repeated int64 n64Datas = 5;
  {
    int data_size = 0;
    for (int i = 0; i < this->n64datas_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int64Size(this->n64datas(i));
    }
    total_size += 1 * this->n64datas_size() + data_size;
  }

  // repeated string strDatas = 6;
  total_size += 1 * this->strdatas_size();
  for (int i = 0; i < this->strdatas_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->strdatas(i));
  }

  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CMsgCommon::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const CMsgCommon*>(&from));
}

void CMsgCommon::MergeFrom(const CMsgCommon& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  ndatas_.MergeFrom(from.ndatas_);
  n64datas_.MergeFrom(from.n64datas_);
  strdatas_.MergeFrom(from.strdatas_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_naction()) {
      set_naction(from.naction());
    }
    if (from.has_idrole()) {
      set_idrole(from.idrole());
    }
    if (from.has_ntype()) {
      set_ntype(from.ntype());
    }
  }
  mutable_unknown_fields()->append(from.unknown_fields());
}

void CMsgCommon::CopyFrom(const CMsgCommon& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CMsgCommon::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void CMsgCommon::Swap(CMsgCommon* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CMsgCommon::InternalSwap(CMsgCommon* other) {
  std::swap(naction_, other->naction_);
  std::swap(idrole_, other->idrole_);
  std::swap(ntype_, other->ntype_);
  ndatas_.UnsafeArenaSwap(&other->ndatas_);
  n64datas_.UnsafeArenaSwap(&other->n64datas_);
  strdatas_.UnsafeArenaSwap(&other->strdatas_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _unknown_fields_.swap(other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string CMsgCommon::GetTypeName() const {
  return "CMsgCommon";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CMsgCommon

// required int32 nAction = 1;
bool CMsgCommon::has_naction() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void CMsgCommon::set_has_naction() {
  _has_bits_[0] |= 0x00000001u;
}
void CMsgCommon::clear_has_naction() {
  _has_bits_[0] &= ~0x00000001u;
}
void CMsgCommon::clear_naction() {
  naction_ = 0;
  clear_has_naction();
}
 ::google::protobuf::int32 CMsgCommon::naction() const {
  // @@protoc_insertion_point(field_get:CMsgCommon.nAction)
  return naction_;
}
 void CMsgCommon::set_naction(::google::protobuf::int32 value) {
  set_has_naction();
  naction_ = value;
  // @@protoc_insertion_point(field_set:CMsgCommon.nAction)
}

// optional uint64 idRole = 2;
bool CMsgCommon::has_idrole() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void CMsgCommon::set_has_idrole() {
  _has_bits_[0] |= 0x00000002u;
}
void CMsgCommon::clear_has_idrole() {
  _has_bits_[0] &= ~0x00000002u;
}
void CMsgCommon::clear_idrole() {
  idrole_ = GOOGLE_ULONGLONG(0);
  clear_has_idrole();
}
 ::google::protobuf::uint64 CMsgCommon::idrole() const {
  // @@protoc_insertion_point(field_get:CMsgCommon.idRole)
  return idrole_;
}
 void CMsgCommon::set_idrole(::google::protobuf::uint64 value) {
  set_has_idrole();
  idrole_ = value;
  // @@protoc_insertion_point(field_set:CMsgCommon.idRole)
}

// optional int64 nType = 3;
bool CMsgCommon::has_ntype() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void CMsgCommon::set_has_ntype() {
  _has_bits_[0] |= 0x00000004u;
}
void CMsgCommon::clear_has_ntype() {
  _has_bits_[0] &= ~0x00000004u;
}
void CMsgCommon::clear_ntype() {
  ntype_ = GOOGLE_LONGLONG(0);
  clear_has_ntype();
}
 ::google::protobuf::int64 CMsgCommon::ntype() const {
  // @@protoc_insertion_point(field_get:CMsgCommon.nType)
  return ntype_;
}
 void CMsgCommon::set_ntype(::google::protobuf::int64 value) {
  set_has_ntype();
  ntype_ = value;
  // @@protoc_insertion_point(field_set:CMsgCommon.nType)
}

// repeated int32 nDatas = 4;
int CMsgCommon::ndatas_size() const {
  return ndatas_.size();
}
void CMsgCommon::clear_ndatas() {
  ndatas_.Clear();
}
 ::google::protobuf::int32 CMsgCommon::ndatas(int index) const {
  // @@protoc_insertion_point(field_get:CMsgCommon.nDatas)
  return ndatas_.Get(index);
}
 void CMsgCommon::set_ndatas(int index, ::google::protobuf::int32 value) {
  ndatas_.Set(index, value);
  // @@protoc_insertion_point(field_set:CMsgCommon.nDatas)
}
 void CMsgCommon::add_ndatas(::google::protobuf::int32 value) {
  ndatas_.Add(value);
  // @@protoc_insertion_point(field_add:CMsgCommon.nDatas)
}
 const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
CMsgCommon::ndatas() const {
  // @@protoc_insertion_point(field_list:CMsgCommon.nDatas)
  return ndatas_;
}
 ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
CMsgCommon::mutable_ndatas() {
  // @@protoc_insertion_point(field_mutable_list:CMsgCommon.nDatas)
  return &ndatas_;
}

// repeated int64 n64Datas = 5;
int CMsgCommon::n64datas_size() const {
  return n64datas_.size();
}
void CMsgCommon::clear_n64datas() {
  n64datas_.Clear();
}
 ::google::protobuf::int64 CMsgCommon::n64datas(int index) const {
  // @@protoc_insertion_point(field_get:CMsgCommon.n64Datas)
  return n64datas_.Get(index);
}
 void CMsgCommon::set_n64datas(int index, ::google::protobuf::int64 value) {
  n64datas_.Set(index, value);
  // @@protoc_insertion_point(field_set:CMsgCommon.n64Datas)
}
 void CMsgCommon::add_n64datas(::google::protobuf::int64 value) {
  n64datas_.Add(value);
  // @@protoc_insertion_point(field_add:CMsgCommon.n64Datas)
}
 const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
CMsgCommon::n64datas() const {
  // @@protoc_insertion_point(field_list:CMsgCommon.n64Datas)
  return n64datas_;
}
 ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
CMsgCommon::mutable_n64datas() {
  // @@protoc_insertion_point(field_mutable_list:CMsgCommon.n64Datas)
  return &n64datas_;
}

// repeated string strDatas = 6;
int CMsgCommon::strdatas_size() const {
  return strdatas_.size();
}
void CMsgCommon::clear_strdatas() {
  strdatas_.Clear();
}
 const ::std::string& CMsgCommon::strdatas(int index) const {
  // @@protoc_insertion_point(field_get:CMsgCommon.strDatas)
  return strdatas_.Get(index);
}
 ::std::string* CMsgCommon::mutable_strdatas(int index) {
  // @@protoc_insertion_point(field_mutable:CMsgCommon.strDatas)
  return strdatas_.Mutable(index);
}
 void CMsgCommon::set_strdatas(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:CMsgCommon.strDatas)
  strdatas_.Mutable(index)->assign(value);
}
 void CMsgCommon::set_strdatas(int index, const char* value) {
  strdatas_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:CMsgCommon.strDatas)
}
 void CMsgCommon::set_strdatas(int index, const char* value, size_t size) {
  strdatas_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:CMsgCommon.strDatas)
}
 ::std::string* CMsgCommon::add_strdatas() {
  return strdatas_.Add();
}
 void CMsgCommon::add_strdatas(const ::std::string& value) {
  strdatas_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:CMsgCommon.strDatas)
}
 void CMsgCommon::add_strdatas(const char* value) {
  strdatas_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:CMsgCommon.strDatas)
}
 void CMsgCommon::add_strdatas(const char* value, size_t size) {
  strdatas_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:CMsgCommon.strDatas)
}
 const ::google::protobuf::RepeatedPtrField< ::std::string>&
CMsgCommon::strdatas() const {
  // @@protoc_insertion_point(field_list:CMsgCommon.strDatas)
  return strdatas_;
}
 ::google::protobuf::RepeatedPtrField< ::std::string>*
CMsgCommon::mutable_strdatas() {
  // @@protoc_insertion_point(field_mutable_list:CMsgCommon.strDatas)
  return &strdatas_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
