// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgConnect.proto

#ifndef PROTOBUF_MsgConnect_2eproto__INCLUDED
#define PROTOBUF_MsgConnect_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_MsgConnect_2eproto();
void protobuf_AssignDesc_MsgConnect_2eproto();
void protobuf_ShutdownFile_MsgConnect_2eproto();

class CMsgConnect;

// ===================================================================

class CMsgConnect : public ::google::protobuf::MessageLite {
 public:
  CMsgConnect();
  virtual ~CMsgConnect();

  CMsgConnect(const CMsgConnect& from);

  inline CMsgConnect& operator=(const CMsgConnect& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const CMsgConnect& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const CMsgConnect* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(CMsgConnect* other);

  // implements Message ----------------------------------------------

  inline CMsgConnect* New() const { return New(NULL); }

  CMsgConnect* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const CMsgConnect& from);
  void MergeFrom(const CMsgConnect& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CMsgConnect* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 idAccount = 1;
  bool has_idaccount() const;
  void clear_idaccount();
  static const int kIdAccountFieldNumber = 1;
  ::google::protobuf::uint64 idaccount() const;
  void set_idaccount(::google::protobuf::uint64 value);

  // optional string szSessionID = 2;
  bool has_szsessionid() const;
  void clear_szsessionid();
  static const int kSzSessionIDFieldNumber = 2;
  const ::std::string& szsessionid() const;
  void set_szsessionid(const ::std::string& value);
  void set_szsessionid(const char* value);
  void set_szsessionid(const char* value, size_t size);
  ::std::string* mutable_szsessionid();
  ::std::string* release_szsessionid();
  void set_allocated_szsessionid(::std::string* szsessionid);

  // @@protoc_insertion_point(class_scope:CMsgConnect)
 private:
  inline void set_has_idaccount();
  inline void clear_has_idaccount();
  inline void set_has_szsessionid();
  inline void clear_has_szsessionid();

  ::std::string _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 idaccount_;
  ::google::protobuf::internal::ArenaStringPtr szsessionid_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_MsgConnect_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_MsgConnect_2eproto();
  #endif
  friend void protobuf_AssignDesc_MsgConnect_2eproto();
  friend void protobuf_ShutdownFile_MsgConnect_2eproto();

  void InitAsDefaultInstance();
  static CMsgConnect* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CMsgConnect

// required uint64 idAccount = 1;
inline bool CMsgConnect::has_idaccount() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CMsgConnect::set_has_idaccount() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CMsgConnect::clear_has_idaccount() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CMsgConnect::clear_idaccount() {
  idaccount_ = GOOGLE_ULONGLONG(0);
  clear_has_idaccount();
}
inline ::google::protobuf::uint64 CMsgConnect::idaccount() const {
  // @@protoc_insertion_point(field_get:CMsgConnect.idAccount)
  return idaccount_;
}
inline void CMsgConnect::set_idaccount(::google::protobuf::uint64 value) {
  set_has_idaccount();
  idaccount_ = value;
  // @@protoc_insertion_point(field_set:CMsgConnect.idAccount)
}

// optional string szSessionID = 2;
inline bool CMsgConnect::has_szsessionid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CMsgConnect::set_has_szsessionid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CMsgConnect::clear_has_szsessionid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CMsgConnect::clear_szsessionid() {
  szsessionid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_szsessionid();
}
inline const ::std::string& CMsgConnect::szsessionid() const {
  // @@protoc_insertion_point(field_get:CMsgConnect.szSessionID)
  return szsessionid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMsgConnect::set_szsessionid(const ::std::string& value) {
  set_has_szsessionid();
  szsessionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CMsgConnect.szSessionID)
}
inline void CMsgConnect::set_szsessionid(const char* value) {
  set_has_szsessionid();
  szsessionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CMsgConnect.szSessionID)
}
inline void CMsgConnect::set_szsessionid(const char* value, size_t size) {
  set_has_szsessionid();
  szsessionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CMsgConnect.szSessionID)
}
inline ::std::string* CMsgConnect::mutable_szsessionid() {
  set_has_szsessionid();
  // @@protoc_insertion_point(field_mutable:CMsgConnect.szSessionID)
  return szsessionid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CMsgConnect::release_szsessionid() {
  clear_has_szsessionid();
  return szsessionid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMsgConnect::set_allocated_szsessionid(::std::string* szsessionid) {
  if (szsessionid != NULL) {
    set_has_szsessionid();
  } else {
    clear_has_szsessionid();
  }
  szsessionid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), szsessionid);
  // @@protoc_insertion_point(field_set_allocated:CMsgConnect.szSessionID)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MsgConnect_2eproto__INCLUDED
