// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgCommon.proto

#ifndef PROTOBUF_MsgCommon_2eproto__INCLUDED
#define PROTOBUF_MsgCommon_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_MsgCommon_2eproto();
void protobuf_AssignDesc_MsgCommon_2eproto();
void protobuf_ShutdownFile_MsgCommon_2eproto();

class CMsgCommon;

enum MSGCOMMON_ACTION {
  COMMONACT_NONE = 0
};
bool MSGCOMMON_ACTION_IsValid(int value);
const MSGCOMMON_ACTION MSGCOMMON_ACTION_MIN = COMMONACT_NONE;
const MSGCOMMON_ACTION MSGCOMMON_ACTION_MAX = COMMONACT_NONE;
const int MSGCOMMON_ACTION_ARRAYSIZE = MSGCOMMON_ACTION_MAX + 1;

// ===================================================================

class CMsgCommon : public ::google::protobuf::MessageLite {
 public:
  CMsgCommon();
  virtual ~CMsgCommon();

  CMsgCommon(const CMsgCommon& from);

  inline CMsgCommon& operator=(const CMsgCommon& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const CMsgCommon& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const CMsgCommon* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(CMsgCommon* other);

  // implements Message ----------------------------------------------

  inline CMsgCommon* New() const { return New(NULL); }

  CMsgCommon* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const CMsgCommon& from);
  void MergeFrom(const CMsgCommon& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CMsgCommon* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 nAction = 1;
  bool has_naction() const;
  void clear_naction();
  static const int kNActionFieldNumber = 1;
  ::google::protobuf::int32 naction() const;
  void set_naction(::google::protobuf::int32 value);

  // optional uint64 idRole = 2;
  bool has_idrole() const;
  void clear_idrole();
  static const int kIdRoleFieldNumber = 2;
  ::google::protobuf::uint64 idrole() const;
  void set_idrole(::google::protobuf::uint64 value);

  // optional int64 nType = 3;
  bool has_ntype() const;
  void clear_ntype();
  static const int kNTypeFieldNumber = 3;
  ::google::protobuf::int64 ntype() const;
  void set_ntype(::google::protobuf::int64 value);

  // repeated int32 nDatas = 4;
  int ndatas_size() const;
  void clear_ndatas();
  static const int kNDatasFieldNumber = 4;
  ::google::protobuf::int32 ndatas(int index) const;
  void set_ndatas(int index, ::google::protobuf::int32 value);
  void add_ndatas(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      ndatas() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_ndatas();

  // repeated int64 n64Datas = 5;
  int n64datas_size() const;
  void clear_n64datas();
  static const int kN64DatasFieldNumber = 5;
  ::google::protobuf::int64 n64datas(int index) const;
  void set_n64datas(int index, ::google::protobuf::int64 value);
  void add_n64datas(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      n64datas() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_n64datas();

  // repeated string strDatas = 6;
  int strdatas_size() const;
  void clear_strdatas();
  static const int kStrDatasFieldNumber = 6;
  const ::std::string& strdatas(int index) const;
  ::std::string* mutable_strdatas(int index);
  void set_strdatas(int index, const ::std::string& value);
  void set_strdatas(int index, const char* value);
  void set_strdatas(int index, const char* value, size_t size);
  ::std::string* add_strdatas();
  void add_strdatas(const ::std::string& value);
  void add_strdatas(const char* value);
  void add_strdatas(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& strdatas() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_strdatas();

  // @@protoc_insertion_point(class_scope:CMsgCommon)
 private:
  inline void set_has_naction();
  inline void clear_has_naction();
  inline void set_has_idrole();
  inline void clear_has_idrole();
  inline void set_has_ntype();
  inline void clear_has_ntype();

  ::std::string _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 idrole_;
  ::google::protobuf::int64 ntype_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > ndatas_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > n64datas_;
  ::google::protobuf::RepeatedPtrField< ::std::string> strdatas_;
  ::google::protobuf::int32 naction_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_MsgCommon_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_MsgCommon_2eproto();
  #endif
  friend void protobuf_AssignDesc_MsgCommon_2eproto();
  friend void protobuf_ShutdownFile_MsgCommon_2eproto();

  void InitAsDefaultInstance();
  static CMsgCommon* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CMsgCommon

// required int32 nAction = 1;
inline bool CMsgCommon::has_naction() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CMsgCommon::set_has_naction() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CMsgCommon::clear_has_naction() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CMsgCommon::clear_naction() {
  naction_ = 0;
  clear_has_naction();
}
inline ::google::protobuf::int32 CMsgCommon::naction() const {
  // @@protoc_insertion_point(field_get:CMsgCommon.nAction)
  return naction_;
}
inline void CMsgCommon::set_naction(::google::protobuf::int32 value) {
  set_has_naction();
  naction_ = value;
  // @@protoc_insertion_point(field_set:CMsgCommon.nAction)
}

// optional uint64 idRole = 2;
inline bool CMsgCommon::has_idrole() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CMsgCommon::set_has_idrole() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CMsgCommon::clear_has_idrole() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CMsgCommon::clear_idrole() {
  idrole_ = GOOGLE_ULONGLONG(0);
  clear_has_idrole();
}
inline ::google::protobuf::uint64 CMsgCommon::idrole() const {
  // @@protoc_insertion_point(field_get:CMsgCommon.idRole)
  return idrole_;
}
inline void CMsgCommon::set_idrole(::google::protobuf::uint64 value) {
  set_has_idrole();
  idrole_ = value;
  // @@protoc_insertion_point(field_set:CMsgCommon.idRole)
}

// optional int64 nType = 3;
inline bool CMsgCommon::has_ntype() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CMsgCommon::set_has_ntype() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CMsgCommon::clear_has_ntype() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CMsgCommon::clear_ntype() {
  ntype_ = GOOGLE_LONGLONG(0);
  clear_has_ntype();
}
inline ::google::protobuf::int64 CMsgCommon::ntype() const {
  // @@protoc_insertion_point(field_get:CMsgCommon.nType)
  return ntype_;
}
inline void CMsgCommon::set_ntype(::google::protobuf::int64 value) {
  set_has_ntype();
  ntype_ = value;
  // @@protoc_insertion_point(field_set:CMsgCommon.nType)
}

// repeated int32 nDatas = 4;
inline int CMsgCommon::ndatas_size() const {
  return ndatas_.size();
}
inline void CMsgCommon::clear_ndatas() {
  ndatas_.Clear();
}
inline ::google::protobuf::int32 CMsgCommon::ndatas(int index) const {
  // @@protoc_insertion_point(field_get:CMsgCommon.nDatas)
  return ndatas_.Get(index);
}
inline void CMsgCommon::set_ndatas(int index, ::google::protobuf::int32 value) {
  ndatas_.Set(index, value);
  // @@protoc_insertion_point(field_set:CMsgCommon.nDatas)
}
inline void CMsgCommon::add_ndatas(::google::protobuf::int32 value) {
  ndatas_.Add(value);
  // @@protoc_insertion_point(field_add:CMsgCommon.nDatas)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
CMsgCommon::ndatas() const {
  // @@protoc_insertion_point(field_list:CMsgCommon.nDatas)
  return ndatas_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
CMsgCommon::mutable_ndatas() {
  // @@protoc_insertion_point(field_mutable_list:CMsgCommon.nDatas)
  return &ndatas_;
}

// repeated int64 n64Datas = 5;
inline int CMsgCommon::n64datas_size() const {
  return n64datas_.size();
}
inline void CMsgCommon::clear_n64datas() {
  n64datas_.Clear();
}
inline ::google::protobuf::int64 CMsgCommon::n64datas(int index) const {
  // @@protoc_insertion_point(field_get:CMsgCommon.n64Datas)
  return n64datas_.Get(index);
}
inline void CMsgCommon::set_n64datas(int index, ::google::protobuf::int64 value) {
  n64datas_.Set(index, value);
  // @@protoc_insertion_point(field_set:CMsgCommon.n64Datas)
}
inline void CMsgCommon::add_n64datas(::google::protobuf::int64 value) {
  n64datas_.Add(value);
  // @@protoc_insertion_point(field_add:CMsgCommon.n64Datas)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
CMsgCommon::n64datas() const {
  // @@protoc_insertion_point(field_list:CMsgCommon.n64Datas)
  return n64datas_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
CMsgCommon::mutable_n64datas() {
  // @@protoc_insertion_point(field_mutable_list:CMsgCommon.n64Datas)
  return &n64datas_;
}

// repeated string strDatas = 6;
inline int CMsgCommon::strdatas_size() const {
  return strdatas_.size();
}
inline void CMsgCommon::clear_strdatas() {
  strdatas_.Clear();
}
inline const ::std::string& CMsgCommon::strdatas(int index) const {
  // @@protoc_insertion_point(field_get:CMsgCommon.strDatas)
  return strdatas_.Get(index);
}
inline ::std::string* CMsgCommon::mutable_strdatas(int index) {
  // @@protoc_insertion_point(field_mutable:CMsgCommon.strDatas)
  return strdatas_.Mutable(index);
}
inline void CMsgCommon::set_strdatas(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:CMsgCommon.strDatas)
  strdatas_.Mutable(index)->assign(value);
}
inline void CMsgCommon::set_strdatas(int index, const char* value) {
  strdatas_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:CMsgCommon.strDatas)
}
inline void CMsgCommon::set_strdatas(int index, const char* value, size_t size) {
  strdatas_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:CMsgCommon.strDatas)
}
inline ::std::string* CMsgCommon::add_strdatas() {
  return strdatas_.Add();
}
inline void CMsgCommon::add_strdatas(const ::std::string& value) {
  strdatas_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:CMsgCommon.strDatas)
}
inline void CMsgCommon::add_strdatas(const char* value) {
  strdatas_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:CMsgCommon.strDatas)
}
inline void CMsgCommon::add_strdatas(const char* value, size_t size) {
  strdatas_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:CMsgCommon.strDatas)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
CMsgCommon::strdatas() const {
  // @@protoc_insertion_point(field_list:CMsgCommon.strDatas)
  return strdatas_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
CMsgCommon::mutable_strdatas() {
  // @@protoc_insertion_point(field_mutable_list:CMsgCommon.strDatas)
  return &strdatas_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::MSGCOMMON_ACTION> : ::google::protobuf::internal::true_type {};

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MsgCommon_2eproto__INCLUDED
