// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgError.proto

#ifndef PROTOBUF_MsgError_2eproto__INCLUDED
#define PROTOBUF_MsgError_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_MsgError_2eproto();
void protobuf_AssignDesc_MsgError_2eproto();
void protobuf_ShutdownFile_MsgError_2eproto();

class CMsgError;

enum MSG_ERROR_ACTION {
  ERRACT_NONE = 0,
  ERRACT_LOGIN_FAILED = 1,
  ERRACT_REGISTER_FAILED = 2
};
bool MSG_ERROR_ACTION_IsValid(int value);
const MSG_ERROR_ACTION MSG_ERROR_ACTION_MIN = ERRACT_NONE;
const MSG_ERROR_ACTION MSG_ERROR_ACTION_MAX = ERRACT_REGISTER_FAILED;
const int MSG_ERROR_ACTION_ARRAYSIZE = MSG_ERROR_ACTION_MAX + 1;

// ===================================================================

class CMsgError : public ::google::protobuf::MessageLite {
 public:
  CMsgError();
  virtual ~CMsgError();

  CMsgError(const CMsgError& from);

  inline CMsgError& operator=(const CMsgError& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const CMsgError& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const CMsgError* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(CMsgError* other);

  // implements Message ----------------------------------------------

  inline CMsgError* New() const { return New(NULL); }

  CMsgError* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const CMsgError& from);
  void MergeFrom(const CMsgError& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CMsgError* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 nAction = 1;
  bool has_naction() const;
  void clear_naction();
  static const int kNActionFieldNumber = 1;
  ::google::protobuf::int32 naction() const;
  void set_naction(::google::protobuf::int32 value);

  // optional int32 nErrorCode = 2;
  bool has_nerrorcode() const;
  void clear_nerrorcode();
  static const int kNErrorCodeFieldNumber = 2;
  ::google::protobuf::int32 nerrorcode() const;
  void set_nerrorcode(::google::protobuf::int32 value);

  // optional string strReason = 3;
  bool has_strreason() const;
  void clear_strreason();
  static const int kStrReasonFieldNumber = 3;
  const ::std::string& strreason() const;
  void set_strreason(const ::std::string& value);
  void set_strreason(const char* value);
  void set_strreason(const char* value, size_t size);
  ::std::string* mutable_strreason();
  ::std::string* release_strreason();
  void set_allocated_strreason(::std::string* strreason);

  // @@protoc_insertion_point(class_scope:CMsgError)
 private:
  inline void set_has_naction();
  inline void clear_has_naction();
  inline void set_has_nerrorcode();
  inline void clear_has_nerrorcode();
  inline void set_has_strreason();
  inline void clear_has_strreason();

  ::std::string _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 naction_;
  ::google::protobuf::int32 nerrorcode_;
  ::google::protobuf::internal::ArenaStringPtr strreason_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_MsgError_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_MsgError_2eproto();
  #endif
  friend void protobuf_AssignDesc_MsgError_2eproto();
  friend void protobuf_ShutdownFile_MsgError_2eproto();

  void InitAsDefaultInstance();
  static CMsgError* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CMsgError

// required int32 nAction = 1;
inline bool CMsgError::has_naction() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CMsgError::set_has_naction() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CMsgError::clear_has_naction() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CMsgError::clear_naction() {
  naction_ = 0;
  clear_has_naction();
}
inline ::google::protobuf::int32 CMsgError::naction() const {
  // @@protoc_insertion_point(field_get:CMsgError.nAction)
  return naction_;
}
inline void CMsgError::set_naction(::google::protobuf::int32 value) {
  set_has_naction();
  naction_ = value;
  // @@protoc_insertion_point(field_set:CMsgError.nAction)
}

// optional int32 nErrorCode = 2;
inline bool CMsgError::has_nerrorcode() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CMsgError::set_has_nerrorcode() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CMsgError::clear_has_nerrorcode() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CMsgError::clear_nerrorcode() {
  nerrorcode_ = 0;
  clear_has_nerrorcode();
}
inline ::google::protobuf::int32 CMsgError::nerrorcode() const {
  // @@protoc_insertion_point(field_get:CMsgError.nErrorCode)
  return nerrorcode_;
}
inline void CMsgError::set_nerrorcode(::google::protobuf::int32 value) {
  set_has_nerrorcode();
  nerrorcode_ = value;
  // @@protoc_insertion_point(field_set:CMsgError.nErrorCode)
}

// optional string strReason = 3;
inline bool CMsgError::has_strreason() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CMsgError::set_has_strreason() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CMsgError::clear_has_strreason() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CMsgError::clear_strreason() {
  strreason_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_strreason();
}
inline const ::std::string& CMsgError::strreason() const {
  // @@protoc_insertion_point(field_get:CMsgError.strReason)
  return strreason_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMsgError::set_strreason(const ::std::string& value) {
  set_has_strreason();
  strreason_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CMsgError.strReason)
}
inline void CMsgError::set_strreason(const char* value) {
  set_has_strreason();
  strreason_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CMsgError.strReason)
}
inline void CMsgError::set_strreason(const char* value, size_t size) {
  set_has_strreason();
  strreason_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CMsgError.strReason)
}
inline ::std::string* CMsgError::mutable_strreason() {
  set_has_strreason();
  // @@protoc_insertion_point(field_mutable:CMsgError.strReason)
  return strreason_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CMsgError::release_strreason() {
  clear_has_strreason();
  return strreason_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMsgError::set_allocated_strreason(::std::string* strreason) {
  if (strreason != NULL) {
    set_has_strreason();
  } else {
    clear_has_strreason();
  }
  strreason_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strreason);
  // @@protoc_insertion_point(field_set_allocated:CMsgError.strReason)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::MSG_ERROR_ACTION> : ::google::protobuf::internal::true_type {};

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MsgError_2eproto__INCLUDED
