// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgError.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MsgError.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

void protobuf_ShutdownFile_MsgError_2eproto() {
  delete CMsgError::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_MsgError_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_MsgError_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  CMsgError::default_instance_ = new CMsgError();
  CMsgError::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MsgError_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_MsgError_2eproto_once_);
void protobuf_AddDesc_MsgError_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_MsgError_2eproto_once_,
                 &protobuf_AddDesc_MsgError_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MsgError_2eproto {
  StaticDescriptorInitializer_MsgError_2eproto() {
    protobuf_AddDesc_MsgError_2eproto();
  }
} static_descriptor_initializer_MsgError_2eproto_;
#endif
bool MSG_ERROR_ACTION_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int CMsgError::kNActionFieldNumber;
const int CMsgError::kNErrorCodeFieldNumber;
const int CMsgError::kStrReasonFieldNumber;
#endif  // !_MSC_VER

CMsgError::CMsgError()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CMsgError)
}

void CMsgError::InitAsDefaultInstance() {
}

CMsgError::CMsgError(const CMsgError& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CMsgError)
}

void CMsgError::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  naction_ = 0;
  nerrorcode_ = 0;
  strreason_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CMsgError::~CMsgError() {
  // @@protoc_insertion_point(destructor:CMsgError)
  SharedDtor();
}

void CMsgError::SharedDtor() {
  strreason_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void CMsgError::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const CMsgError& CMsgError::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_MsgError_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_MsgError_2eproto();
#endif
  return *default_instance_;
}

CMsgError* CMsgError::default_instance_ = NULL;

CMsgError* CMsgError::New(::google::protobuf::Arena* arena) const {
  CMsgError* n = new CMsgError;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CMsgError::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<CMsgError*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  if (_has_bits_[0 / 32] & 7u) {
    ZR_(naction_, nerrorcode_);
    if (has_strreason()) {
      strreason_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->clear();
}

bool CMsgError::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::StringOutputStream unknown_fields_string(
      mutable_unknown_fields());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string);
  // @@protoc_insertion_point(parse_start:CMsgError)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 nAction = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &naction_)));
          set_has_naction();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_nErrorCode;
        break;
      }

      // optional int32 nErrorCode = 2;
      case 2: {
        if (tag == 16) {
         parse_nErrorCode:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &nerrorcode_)));
          set_has_nerrorcode();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_strReason;
        break;
      }

      // optional string strReason = 3;
      case 3: {
        if (tag == 26) {
         parse_strReason:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_strreason()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CMsgError)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CMsgError)
  return false;
#undef DO_
}

void CMsgError::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CMsgError)
  // required int32 nAction = 1;
  if (has_naction()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->naction(), output);
  }

  // optional int32 nErrorCode = 2;
  if (has_nerrorcode()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->nerrorcode(), output);
  }

  // optional string strReason = 3;
  if (has_strreason()) {
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->strreason(), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   unknown_fields().size());
  // @@protoc_insertion_point(serialize_end:CMsgError)
}

int CMsgError::ByteSize() const {
  int total_size = 0;

  // required int32 nAction = 1;
  if (has_naction()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->naction());
  }
  if (_has_bits_[1 / 32] & 6u) {
    // optional int32 nErrorCode = 2;
    if (has_nerrorcode()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->nerrorcode());
    }

    // optional string strReason = 3;
    if (has_strreason()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->strreason());
    }

  }
  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CMsgError::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const CMsgError*>(&from));
}

void CMsgError::MergeFrom(const CMsgError& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_naction()) {
      set_naction(from.naction());
    }
    if (from.has_nerrorcode()) {
      set_nerrorcode(from.nerrorcode());
    }
    if (from.has_strreason()) {
      set_has_strreason();
      strreason_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strreason_);
    }
  }
  mutable_unknown_fields()->append(from.unknown_fields());
}

void CMsgError::CopyFrom(const CMsgError& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CMsgError::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void CMsgError::Swap(CMsgError* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CMsgError::InternalSwap(CMsgError* other) {
  std::swap(naction_, other->naction_);
  std::swap(nerrorcode_, other->nerrorcode_);
  strreason_.Swap(&other->strreason_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _unknown_fields_.swap(other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string CMsgError::GetTypeName() const {
  return "CMsgError";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CMsgError

// required int32 nAction = 1;
bool CMsgError::has_naction() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void CMsgError::set_has_naction() {
  _has_bits_[0] |= 0x00000001u;
}
void CMsgError::clear_has_naction() {
  _has_bits_[0] &= ~0x00000001u;
}
void CMsgError::clear_naction() {
  naction_ = 0;
  clear_has_naction();
}
 ::google::protobuf::int32 CMsgError::naction() const {
  // @@protoc_insertion_point(field_get:CMsgError.nAction)
  return naction_;
}
 void CMsgError::set_naction(::google::protobuf::int32 value) {
  set_has_naction();
  naction_ = value;
  // @@protoc_insertion_point(field_set:CMsgError.nAction)
}

// optional int32 nErrorCode = 2;
bool CMsgError::has_nerrorcode() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void CMsgError::set_has_nerrorcode() {
  _has_bits_[0] |= 0x00000002u;
}
void CMsgError::clear_has_nerrorcode() {
  _has_bits_[0] &= ~0x00000002u;
}
void CMsgError::clear_nerrorcode() {
  nerrorcode_ = 0;
  clear_has_nerrorcode();
}
 ::google::protobuf::int32 CMsgError::nerrorcode() const {
  // @@protoc_insertion_point(field_get:CMsgError.nErrorCode)
  return nerrorcode_;
}
 void CMsgError::set_nerrorcode(::google::protobuf::int32 value) {
  set_has_nerrorcode();
  nerrorcode_ = value;
  // @@protoc_insertion_point(field_set:CMsgError.nErrorCode)
}

// optional string strReason = 3;
bool CMsgError::has_strreason() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void CMsgError::set_has_strreason() {
  _has_bits_[0] |= 0x00000004u;
}
void CMsgError::clear_has_strreason() {
  _has_bits_[0] &= ~0x00000004u;
}
void CMsgError::clear_strreason() {
  strreason_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_strreason();
}
 const ::std::string& CMsgError::strreason() const {
  // @@protoc_insertion_point(field_get:CMsgError.strReason)
  return strreason_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CMsgError::set_strreason(const ::std::string& value) {
  set_has_strreason();
  strreason_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CMsgError.strReason)
}
 void CMsgError::set_strreason(const char* value) {
  set_has_strreason();
  strreason_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CMsgError.strReason)
}
 void CMsgError::set_strreason(const char* value, size_t size) {
  set_has_strreason();
  strreason_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CMsgError.strReason)
}
 ::std::string* CMsgError::mutable_strreason() {
  set_has_strreason();
  // @@protoc_insertion_point(field_mutable:CMsgError.strReason)
  return strreason_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* CMsgError::release_strreason() {
  clear_has_strreason();
  return strreason_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CMsgError::set_allocated_strreason(::std::string* strreason) {
  if (strreason != NULL) {
    set_has_strreason();
  } else {
    clear_has_strreason();
  }
  strreason_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strreason);
  // @@protoc_insertion_point(field_set_allocated:CMsgError.strReason)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
