// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgInproc.proto

#ifndef PROTOBUF_MsgInproc_2eproto__INCLUDED
#define PROTOBUF_MsgInproc_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_MsgInproc_2eproto();
void protobuf_AssignDesc_MsgInproc_2eproto();
void protobuf_ShutdownFile_MsgInproc_2eproto();

class CMsgInproc;

enum INPROC_ACTION {
  INPROCACT_NONE = 0,
  INPROCACT_SS_BEGIN = 1,
  INPROCACT_SS_USER_LOGIN_TO_GAME = 2,
  INPROCACT_SS_CLOSE_CONNECTION = 3,
  INPROCACT_SS_END = 10000,
  INPROCACT_LOGIN_BEGIN = 10001,
  INPROCACT_LOGIN_END = 20000,
  INRPOCACT_DB_BEGIN = 20001,
  INPROCACT_DB_LOAD_USER = 20002,
  INRPOCACT_DB_END = 30000,
  INPROCACT_GAME_BEGIN = 30001,
  INPROCACT_GAME_LOAD_USER_FINISHED = 30002,
  INPROCACT_GAME_USER_REQUEST_LOGIN = 30003,
  INPROCACT_GAME_USER_DISCONNECTED = 30004,
  INPROCACT_GAME_TEST_CMD = 30005,
  INPROCACT_GAME_END = 40000,
  INPROCACT_AS_BEGIN = 40001,
  INPROCACT_AS_END = 40002
};
bool INPROC_ACTION_IsValid(int value);
const INPROC_ACTION INPROC_ACTION_MIN = INPROCACT_NONE;
const INPROC_ACTION INPROC_ACTION_MAX = INPROCACT_AS_END;
const int INPROC_ACTION_ARRAYSIZE = INPROC_ACTION_MAX + 1;

// ===================================================================

class CMsgInproc : public ::google::protobuf::MessageLite {
 public:
  CMsgInproc();
  virtual ~CMsgInproc();

  CMsgInproc(const CMsgInproc& from);

  inline CMsgInproc& operator=(const CMsgInproc& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const CMsgInproc& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const CMsgInproc* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(CMsgInproc* other);

  // implements Message ----------------------------------------------

  inline CMsgInproc* New() const { return New(NULL); }

  CMsgInproc* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const CMsgInproc& from);
  void MergeFrom(const CMsgInproc& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CMsgInproc* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .INPROC_ACTION nAction = 1;
  bool has_naction() const;
  void clear_naction();
  static const int kNActionFieldNumber = 1;
  ::INPROC_ACTION naction() const;
  void set_naction(::INPROC_ACTION value);

  // optional uint64 idRole = 2;
  bool has_idrole() const;
  void clear_idrole();
  static const int kIdRoleFieldNumber = 2;
  ::google::protobuf::uint64 idrole() const;
  void set_idrole(::google::protobuf::uint64 value);

  // repeated uint32 u32Data = 3;
  int u32data_size() const;
  void clear_u32data();
  static const int kU32DataFieldNumber = 3;
  ::google::protobuf::uint32 u32data(int index) const;
  void set_u32data(int index, ::google::protobuf::uint32 value);
  void add_u32data(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      u32data() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_u32data();

  // repeated uint64 u64Data = 4;
  int u64data_size() const;
  void clear_u64data();
  static const int kU64DataFieldNumber = 4;
  ::google::protobuf::uint64 u64data(int index) const;
  void set_u64data(int index, ::google::protobuf::uint64 value);
  void add_u64data(::google::protobuf::uint64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      u64data() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_u64data();

  // repeated float fData = 5;
  int fdata_size() const;
  void clear_fdata();
  static const int kFDataFieldNumber = 5;
  float fdata(int index) const;
  void set_fdata(int index, float value);
  void add_fdata(float value);
  const ::google::protobuf::RepeatedField< float >&
      fdata() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_fdata();

  // repeated string strData = 6;
  int strdata_size() const;
  void clear_strdata();
  static const int kStrDataFieldNumber = 6;
  const ::std::string& strdata(int index) const;
  ::std::string* mutable_strdata(int index);
  void set_strdata(int index, const ::std::string& value);
  void set_strdata(int index, const char* value);
  void set_strdata(int index, const char* value, size_t size);
  ::std::string* add_strdata();
  void add_strdata(const ::std::string& value);
  void add_strdata(const char* value);
  void add_strdata(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& strdata() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_strdata();

  // @@protoc_insertion_point(class_scope:CMsgInproc)
 private:
  inline void set_has_naction();
  inline void clear_has_naction();
  inline void set_has_idrole();
  inline void clear_has_idrole();

  ::std::string _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 idrole_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > u32data_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > u64data_;
  ::google::protobuf::RepeatedField< float > fdata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> strdata_;
  int naction_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_MsgInproc_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_MsgInproc_2eproto();
  #endif
  friend void protobuf_AssignDesc_MsgInproc_2eproto();
  friend void protobuf_ShutdownFile_MsgInproc_2eproto();

  void InitAsDefaultInstance();
  static CMsgInproc* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CMsgInproc

// required .INPROC_ACTION nAction = 1;
inline bool CMsgInproc::has_naction() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CMsgInproc::set_has_naction() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CMsgInproc::clear_has_naction() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CMsgInproc::clear_naction() {
  naction_ = 0;
  clear_has_naction();
}
inline ::INPROC_ACTION CMsgInproc::naction() const {
  // @@protoc_insertion_point(field_get:CMsgInproc.nAction)
  return static_cast< ::INPROC_ACTION >(naction_);
}
inline void CMsgInproc::set_naction(::INPROC_ACTION value) {
  assert(::INPROC_ACTION_IsValid(value));
  set_has_naction();
  naction_ = value;
  // @@protoc_insertion_point(field_set:CMsgInproc.nAction)
}

// optional uint64 idRole = 2;
inline bool CMsgInproc::has_idrole() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CMsgInproc::set_has_idrole() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CMsgInproc::clear_has_idrole() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CMsgInproc::clear_idrole() {
  idrole_ = GOOGLE_ULONGLONG(0);
  clear_has_idrole();
}
inline ::google::protobuf::uint64 CMsgInproc::idrole() const {
  // @@protoc_insertion_point(field_get:CMsgInproc.idRole)
  return idrole_;
}
inline void CMsgInproc::set_idrole(::google::protobuf::uint64 value) {
  set_has_idrole();
  idrole_ = value;
  // @@protoc_insertion_point(field_set:CMsgInproc.idRole)
}

// repeated uint32 u32Data = 3;
inline int CMsgInproc::u32data_size() const {
  return u32data_.size();
}
inline void CMsgInproc::clear_u32data() {
  u32data_.Clear();
}
inline ::google::protobuf::uint32 CMsgInproc::u32data(int index) const {
  // @@protoc_insertion_point(field_get:CMsgInproc.u32Data)
  return u32data_.Get(index);
}
inline void CMsgInproc::set_u32data(int index, ::google::protobuf::uint32 value) {
  u32data_.Set(index, value);
  // @@protoc_insertion_point(field_set:CMsgInproc.u32Data)
}
inline void CMsgInproc::add_u32data(::google::protobuf::uint32 value) {
  u32data_.Add(value);
  // @@protoc_insertion_point(field_add:CMsgInproc.u32Data)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
CMsgInproc::u32data() const {
  // @@protoc_insertion_point(field_list:CMsgInproc.u32Data)
  return u32data_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
CMsgInproc::mutable_u32data() {
  // @@protoc_insertion_point(field_mutable_list:CMsgInproc.u32Data)
  return &u32data_;
}

// repeated uint64 u64Data = 4;
inline int CMsgInproc::u64data_size() const {
  return u64data_.size();
}
inline void CMsgInproc::clear_u64data() {
  u64data_.Clear();
}
inline ::google::protobuf::uint64 CMsgInproc::u64data(int index) const {
  // @@protoc_insertion_point(field_get:CMsgInproc.u64Data)
  return u64data_.Get(index);
}
inline void CMsgInproc::set_u64data(int index, ::google::protobuf::uint64 value) {
  u64data_.Set(index, value);
  // @@protoc_insertion_point(field_set:CMsgInproc.u64Data)
}
inline void CMsgInproc::add_u64data(::google::protobuf::uint64 value) {
  u64data_.Add(value);
  // @@protoc_insertion_point(field_add:CMsgInproc.u64Data)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
CMsgInproc::u64data() const {
  // @@protoc_insertion_point(field_list:CMsgInproc.u64Data)
  return u64data_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
CMsgInproc::mutable_u64data() {
  // @@protoc_insertion_point(field_mutable_list:CMsgInproc.u64Data)
  return &u64data_;
}

// repeated float fData = 5;
inline int CMsgInproc::fdata_size() const {
  return fdata_.size();
}
inline void CMsgInproc::clear_fdata() {
  fdata_.Clear();
}
inline float CMsgInproc::fdata(int index) const {
  // @@protoc_insertion_point(field_get:CMsgInproc.fData)
  return fdata_.Get(index);
}
inline void CMsgInproc::set_fdata(int index, float value) {
  fdata_.Set(index, value);
  // @@protoc_insertion_point(field_set:CMsgInproc.fData)
}
inline void CMsgInproc::add_fdata(float value) {
  fdata_.Add(value);
  // @@protoc_insertion_point(field_add:CMsgInproc.fData)
}
inline const ::google::protobuf::RepeatedField< float >&
CMsgInproc::fdata() const {
  // @@protoc_insertion_point(field_list:CMsgInproc.fData)
  return fdata_;
}
inline ::google::protobuf::RepeatedField< float >*
CMsgInproc::mutable_fdata() {
  // @@protoc_insertion_point(field_mutable_list:CMsgInproc.fData)
  return &fdata_;
}

// repeated string strData = 6;
inline int CMsgInproc::strdata_size() const {
  return strdata_.size();
}
inline void CMsgInproc::clear_strdata() {
  strdata_.Clear();
}
inline const ::std::string& CMsgInproc::strdata(int index) const {
  // @@protoc_insertion_point(field_get:CMsgInproc.strData)
  return strdata_.Get(index);
}
inline ::std::string* CMsgInproc::mutable_strdata(int index) {
  // @@protoc_insertion_point(field_mutable:CMsgInproc.strData)
  return strdata_.Mutable(index);
}
inline void CMsgInproc::set_strdata(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:CMsgInproc.strData)
  strdata_.Mutable(index)->assign(value);
}
inline void CMsgInproc::set_strdata(int index, const char* value) {
  strdata_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:CMsgInproc.strData)
}
inline void CMsgInproc::set_strdata(int index, const char* value, size_t size) {
  strdata_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:CMsgInproc.strData)
}
inline ::std::string* CMsgInproc::add_strdata() {
  return strdata_.Add();
}
inline void CMsgInproc::add_strdata(const ::std::string& value) {
  strdata_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:CMsgInproc.strData)
}
inline void CMsgInproc::add_strdata(const char* value) {
  strdata_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:CMsgInproc.strData)
}
inline void CMsgInproc::add_strdata(const char* value, size_t size) {
  strdata_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:CMsgInproc.strData)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
CMsgInproc::strdata() const {
  // @@protoc_insertion_point(field_list:CMsgInproc.strData)
  return strdata_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
CMsgInproc::mutable_strdata() {
  // @@protoc_insertion_point(field_mutable_list:CMsgInproc.strData)
  return &strdata_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::INPROC_ACTION> : ::google::protobuf::internal::true_type {};

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MsgInproc_2eproto__INCLUDED
