// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgLoginStep.proto

#ifndef PROTOBUF_MsgLoginStep_2eproto__INCLUDED
#define PROTOBUF_MsgLoginStep_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_MsgLoginStep_2eproto();
void protobuf_AssignDesc_MsgLoginStep_2eproto();
void protobuf_ShutdownFile_MsgLoginStep_2eproto();

class CMsgLoginStep;

enum MSG_LOGIN_STEP_ACTION {
  LOGINSTEPACT_NONE = 0,
  LOGINSTEPACT_ENTER_SCENE = 1,
  LOGINSTEPACT_LOGIN_OK = 100
};
bool MSG_LOGIN_STEP_ACTION_IsValid(int value);
const MSG_LOGIN_STEP_ACTION MSG_LOGIN_STEP_ACTION_MIN = LOGINSTEPACT_NONE;
const MSG_LOGIN_STEP_ACTION MSG_LOGIN_STEP_ACTION_MAX = LOGINSTEPACT_LOGIN_OK;
const int MSG_LOGIN_STEP_ACTION_ARRAYSIZE = MSG_LOGIN_STEP_ACTION_MAX + 1;

// ===================================================================

class CMsgLoginStep : public ::google::protobuf::MessageLite {
 public:
  CMsgLoginStep();
  virtual ~CMsgLoginStep();

  CMsgLoginStep(const CMsgLoginStep& from);

  inline CMsgLoginStep& operator=(const CMsgLoginStep& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const CMsgLoginStep& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const CMsgLoginStep* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(CMsgLoginStep* other);

  // implements Message ----------------------------------------------

  inline CMsgLoginStep* New() const { return New(NULL); }

  CMsgLoginStep* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const CMsgLoginStep& from);
  void MergeFrom(const CMsgLoginStep& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CMsgLoginStep* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 nAction = 1;
  bool has_naction() const;
  void clear_naction();
  static const int kNActionFieldNumber = 1;
  ::google::protobuf::int32 naction() const;
  void set_naction(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:CMsgLoginStep)
 private:
  inline void set_has_naction();
  inline void clear_has_naction();

  ::std::string _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 naction_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_MsgLoginStep_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_MsgLoginStep_2eproto();
  #endif
  friend void protobuf_AssignDesc_MsgLoginStep_2eproto();
  friend void protobuf_ShutdownFile_MsgLoginStep_2eproto();

  void InitAsDefaultInstance();
  static CMsgLoginStep* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CMsgLoginStep

// required int32 nAction = 1;
inline bool CMsgLoginStep::has_naction() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CMsgLoginStep::set_has_naction() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CMsgLoginStep::clear_has_naction() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CMsgLoginStep::clear_naction() {
  naction_ = 0;
  clear_has_naction();
}
inline ::google::protobuf::int32 CMsgLoginStep::naction() const {
  // @@protoc_insertion_point(field_get:CMsgLoginStep.nAction)
  return naction_;
}
inline void CMsgLoginStep::set_naction(::google::protobuf::int32 value) {
  set_has_naction();
  naction_ = value;
  // @@protoc_insertion_point(field_set:CMsgLoginStep.nAction)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::MSG_LOGIN_STEP_ACTION> : ::google::protobuf::internal::true_type {};

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MsgLoginStep_2eproto__INCLUDED
