// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgLoginStep.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MsgLoginStep.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

void protobuf_ShutdownFile_MsgLoginStep_2eproto() {
  delete CMsgLoginStep::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_MsgLoginStep_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_MsgLoginStep_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  CMsgLoginStep::default_instance_ = new CMsgLoginStep();
  CMsgLoginStep::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MsgLoginStep_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_MsgLoginStep_2eproto_once_);
void protobuf_AddDesc_MsgLoginStep_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_MsgLoginStep_2eproto_once_,
                 &protobuf_AddDesc_MsgLoginStep_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MsgLoginStep_2eproto {
  StaticDescriptorInitializer_MsgLoginStep_2eproto() {
    protobuf_AddDesc_MsgLoginStep_2eproto();
  }
} static_descriptor_initializer_MsgLoginStep_2eproto_;
#endif
bool MSG_LOGIN_STEP_ACTION_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 100:
      return true;
    default:
      return false;
  }
}


namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int CMsgLoginStep::kNActionFieldNumber;
#endif  // !_MSC_VER

CMsgLoginStep::CMsgLoginStep()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CMsgLoginStep)
}

void CMsgLoginStep::InitAsDefaultInstance() {
}

CMsgLoginStep::CMsgLoginStep(const CMsgLoginStep& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CMsgLoginStep)
}

void CMsgLoginStep::SharedCtor() {
  _cached_size_ = 0;
  naction_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CMsgLoginStep::~CMsgLoginStep() {
  // @@protoc_insertion_point(destructor:CMsgLoginStep)
  SharedDtor();
}

void CMsgLoginStep::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void CMsgLoginStep::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const CMsgLoginStep& CMsgLoginStep::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_MsgLoginStep_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_MsgLoginStep_2eproto();
#endif
  return *default_instance_;
}

CMsgLoginStep* CMsgLoginStep::default_instance_ = NULL;

CMsgLoginStep* CMsgLoginStep::New(::google::protobuf::Arena* arena) const {
  CMsgLoginStep* n = new CMsgLoginStep;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CMsgLoginStep::Clear() {
  naction_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->clear();
}

bool CMsgLoginStep::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::StringOutputStream unknown_fields_string(
      mutable_unknown_fields());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string);
  // @@protoc_insertion_point(parse_start:CMsgLoginStep)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 nAction = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &naction_)));
          set_has_naction();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CMsgLoginStep)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CMsgLoginStep)
  return false;
#undef DO_
}

void CMsgLoginStep::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CMsgLoginStep)
  // required int32 nAction = 1;
  if (has_naction()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->naction(), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   unknown_fields().size());
  // @@protoc_insertion_point(serialize_end:CMsgLoginStep)
}

int CMsgLoginStep::ByteSize() const {
  int total_size = 0;

  // required int32 nAction = 1;
  if (has_naction()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->naction());
  }
  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CMsgLoginStep::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const CMsgLoginStep*>(&from));
}

void CMsgLoginStep::MergeFrom(const CMsgLoginStep& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_naction()) {
      set_naction(from.naction());
    }
  }
  mutable_unknown_fields()->append(from.unknown_fields());
}

void CMsgLoginStep::CopyFrom(const CMsgLoginStep& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CMsgLoginStep::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void CMsgLoginStep::Swap(CMsgLoginStep* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CMsgLoginStep::InternalSwap(CMsgLoginStep* other) {
  std::swap(naction_, other->naction_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _unknown_fields_.swap(other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string CMsgLoginStep::GetTypeName() const {
  return "CMsgLoginStep";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CMsgLoginStep

// required int32 nAction = 1;
bool CMsgLoginStep::has_naction() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void CMsgLoginStep::set_has_naction() {
  _has_bits_[0] |= 0x00000001u;
}
void CMsgLoginStep::clear_has_naction() {
  _has_bits_[0] &= ~0x00000001u;
}
void CMsgLoginStep::clear_naction() {
  naction_ = 0;
  clear_has_naction();
}
 ::google::protobuf::int32 CMsgLoginStep::naction() const {
  // @@protoc_insertion_point(field_get:CMsgLoginStep.nAction)
  return naction_;
}
 void CMsgLoginStep::set_naction(::google::protobuf::int32 value) {
  set_has_naction();
  naction_ = value;
  // @@protoc_insertion_point(field_set:CMsgLoginStep.nAction)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
