// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgRoleInfo.proto

#ifndef PROTOBUF_MsgRoleInfo_2eproto__INCLUDED
#define PROTOBUF_MsgRoleInfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_MsgRoleInfo_2eproto();
void protobuf_AssignDesc_MsgRoleInfo_2eproto();
void protobuf_ShutdownFile_MsgRoleInfo_2eproto();

class CMsgRoleInfo;

enum MSG_ROLE_INFO_ACTION {
  ROLEINFOACT_NONE = 0,
  ROLEINFOACT_SELF_NEW = 1,
  ROLEINFOACT_SELF_UPDATE = 2,
  ROLEINFOACT_OTHER_NEW = 3,
  ROLEINFOACT_OTHER_UPDATE = 4,
  ROLEINFOACT_LEAVE_SCENE = 5
};
bool MSG_ROLE_INFO_ACTION_IsValid(int value);
const MSG_ROLE_INFO_ACTION MSG_ROLE_INFO_ACTION_MIN = ROLEINFOACT_NONE;
const MSG_ROLE_INFO_ACTION MSG_ROLE_INFO_ACTION_MAX = ROLEINFOACT_LEAVE_SCENE;
const int MSG_ROLE_INFO_ACTION_ARRAYSIZE = MSG_ROLE_INFO_ACTION_MAX + 1;

// ===================================================================

class CMsgRoleInfo : public ::google::protobuf::MessageLite {
 public:
  CMsgRoleInfo();
  virtual ~CMsgRoleInfo();

  CMsgRoleInfo(const CMsgRoleInfo& from);

  inline CMsgRoleInfo& operator=(const CMsgRoleInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const CMsgRoleInfo& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const CMsgRoleInfo* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(CMsgRoleInfo* other);

  // implements Message ----------------------------------------------

  inline CMsgRoleInfo* New() const { return New(NULL); }

  CMsgRoleInfo* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const CMsgRoleInfo& from);
  void MergeFrom(const CMsgRoleInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CMsgRoleInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 nAction = 1;
  bool has_naction() const;
  void clear_naction();
  static const int kNActionFieldNumber = 1;
  ::google::protobuf::int32 naction() const;
  void set_naction(::google::protobuf::int32 value);

  // required uint64 idRole = 2;
  bool has_idrole() const;
  void clear_idrole();
  static const int kIdRoleFieldNumber = 2;
  ::google::protobuf::uint64 idrole() const;
  void set_idrole(::google::protobuf::uint64 value);

  // required uint32 nType = 3;
  bool has_ntype() const;
  void clear_ntype();
  static const int kNTypeFieldNumber = 3;
  ::google::protobuf::uint32 ntype() const;
  void set_ntype(::google::protobuf::uint32 value);

  // optional string strName = 4;
  bool has_strname() const;
  void clear_strname();
  static const int kStrNameFieldNumber = 4;
  const ::std::string& strname() const;
  void set_strname(const ::std::string& value);
  void set_strname(const char* value);
  void set_strname(const char* value, size_t size);
  ::std::string* mutable_strname();
  ::std::string* release_strname();
  void set_allocated_strname(::std::string* strname);

  // optional uint32 idRoleType = 5;
  bool has_idroletype() const;
  void clear_idroletype();
  static const int kIdRoleTypeFieldNumber = 5;
  ::google::protobuf::uint32 idroletype() const;
  void set_idroletype(::google::protobuf::uint32 value);

  // optional int32 nLevel = 6;
  bool has_nlevel() const;
  void clear_nlevel();
  static const int kNLevelFieldNumber = 6;
  ::google::protobuf::int32 nlevel() const;
  void set_nlevel(::google::protobuf::int32 value);

  // optional int64 nExp = 7;
  bool has_nexp() const;
  void clear_nexp();
  static const int kNExpFieldNumber = 7;
  ::google::protobuf::int64 nexp() const;
  void set_nexp(::google::protobuf::int64 value);

  // optional float fPos_x = 8;
  bool has_fpos_x() const;
  void clear_fpos_x();
  static const int kFPosXFieldNumber = 8;
  float fpos_x() const;
  void set_fpos_x(float value);

  // optional float fPos_y = 9;
  bool has_fpos_y() const;
  void clear_fpos_y();
  static const int kFPosYFieldNumber = 9;
  float fpos_y() const;
  void set_fpos_y(float value);

  // optional float fPos_z = 10;
  bool has_fpos_z() const;
  void clear_fpos_z();
  static const int kFPosZFieldNumber = 10;
  float fpos_z() const;
  void set_fpos_z(float value);

  // optional int32 nLife = 11;
  bool has_nlife() const;
  void clear_nlife();
  static const int kNLifeFieldNumber = 11;
  ::google::protobuf::int32 nlife() const;
  void set_nlife(::google::protobuf::int32 value);

  // optional int32 nMaxLife = 12;
  bool has_nmaxlife() const;
  void clear_nmaxlife();
  static const int kNMaxLifeFieldNumber = 12;
  ::google::protobuf::int32 nmaxlife() const;
  void set_nmaxlife(::google::protobuf::int32 value);

  // optional int32 nMana = 13;
  bool has_nmana() const;
  void clear_nmana();
  static const int kNManaFieldNumber = 13;
  ::google::protobuf::int32 nmana() const;
  void set_nmana(::google::protobuf::int32 value);

  // optional int32 nMaxMana = 14;
  bool has_nmaxmana() const;
  void clear_nmaxmana();
  static const int kNMaxManaFieldNumber = 14;
  ::google::protobuf::int32 nmaxmana() const;
  void set_nmaxmana(::google::protobuf::int32 value);

  // optional uint32 idScene = 1001;
  bool has_idscene() const;
  void clear_idscene();
  static const int kIdSceneFieldNumber = 1001;
  ::google::protobuf::uint32 idscene() const;
  void set_idscene(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:CMsgRoleInfo)
 private:
  inline void set_has_naction();
  inline void clear_has_naction();
  inline void set_has_idrole();
  inline void clear_has_idrole();
  inline void set_has_ntype();
  inline void clear_has_ntype();
  inline void set_has_strname();
  inline void clear_has_strname();
  inline void set_has_idroletype();
  inline void clear_has_idroletype();
  inline void set_has_nlevel();
  inline void clear_has_nlevel();
  inline void set_has_nexp();
  inline void clear_has_nexp();
  inline void set_has_fpos_x();
  inline void clear_has_fpos_x();
  inline void set_has_fpos_y();
  inline void clear_has_fpos_y();
  inline void set_has_fpos_z();
  inline void clear_has_fpos_z();
  inline void set_has_nlife();
  inline void clear_has_nlife();
  inline void set_has_nmaxlife();
  inline void clear_has_nmaxlife();
  inline void set_has_nmana();
  inline void clear_has_nmana();
  inline void set_has_nmaxmana();
  inline void clear_has_nmaxmana();
  inline void set_has_idscene();
  inline void clear_has_idscene();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::std::string _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 idrole_;
  ::google::protobuf::int32 naction_;
  ::google::protobuf::uint32 ntype_;
  ::google::protobuf::internal::ArenaStringPtr strname_;
  ::google::protobuf::uint32 idroletype_;
  ::google::protobuf::int32 nlevel_;
  ::google::protobuf::int64 nexp_;
  float fpos_x_;
  float fpos_y_;
  float fpos_z_;
  ::google::protobuf::int32 nlife_;
  ::google::protobuf::int32 nmaxlife_;
  ::google::protobuf::int32 nmana_;
  ::google::protobuf::int32 nmaxmana_;
  ::google::protobuf::uint32 idscene_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_MsgRoleInfo_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_MsgRoleInfo_2eproto();
  #endif
  friend void protobuf_AssignDesc_MsgRoleInfo_2eproto();
  friend void protobuf_ShutdownFile_MsgRoleInfo_2eproto();

  void InitAsDefaultInstance();
  static CMsgRoleInfo* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CMsgRoleInfo

// required int32 nAction = 1;
inline bool CMsgRoleInfo::has_naction() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CMsgRoleInfo::set_has_naction() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CMsgRoleInfo::clear_has_naction() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CMsgRoleInfo::clear_naction() {
  naction_ = 0;
  clear_has_naction();
}
inline ::google::protobuf::int32 CMsgRoleInfo::naction() const {
  // @@protoc_insertion_point(field_get:CMsgRoleInfo.nAction)
  return naction_;
}
inline void CMsgRoleInfo::set_naction(::google::protobuf::int32 value) {
  set_has_naction();
  naction_ = value;
  // @@protoc_insertion_point(field_set:CMsgRoleInfo.nAction)
}

// required uint64 idRole = 2;
inline bool CMsgRoleInfo::has_idrole() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CMsgRoleInfo::set_has_idrole() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CMsgRoleInfo::clear_has_idrole() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CMsgRoleInfo::clear_idrole() {
  idrole_ = GOOGLE_ULONGLONG(0);
  clear_has_idrole();
}
inline ::google::protobuf::uint64 CMsgRoleInfo::idrole() const {
  // @@protoc_insertion_point(field_get:CMsgRoleInfo.idRole)
  return idrole_;
}
inline void CMsgRoleInfo::set_idrole(::google::protobuf::uint64 value) {
  set_has_idrole();
  idrole_ = value;
  // @@protoc_insertion_point(field_set:CMsgRoleInfo.idRole)
}

// required uint32 nType = 3;
inline bool CMsgRoleInfo::has_ntype() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CMsgRoleInfo::set_has_ntype() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CMsgRoleInfo::clear_has_ntype() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CMsgRoleInfo::clear_ntype() {
  ntype_ = 0u;
  clear_has_ntype();
}
inline ::google::protobuf::uint32 CMsgRoleInfo::ntype() const {
  // @@protoc_insertion_point(field_get:CMsgRoleInfo.nType)
  return ntype_;
}
inline void CMsgRoleInfo::set_ntype(::google::protobuf::uint32 value) {
  set_has_ntype();
  ntype_ = value;
  // @@protoc_insertion_point(field_set:CMsgRoleInfo.nType)
}

// optional string strName = 4;
inline bool CMsgRoleInfo::has_strname() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CMsgRoleInfo::set_has_strname() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CMsgRoleInfo::clear_has_strname() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CMsgRoleInfo::clear_strname() {
  strname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_strname();
}
inline const ::std::string& CMsgRoleInfo::strname() const {
  // @@protoc_insertion_point(field_get:CMsgRoleInfo.strName)
  return strname_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMsgRoleInfo::set_strname(const ::std::string& value) {
  set_has_strname();
  strname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CMsgRoleInfo.strName)
}
inline void CMsgRoleInfo::set_strname(const char* value) {
  set_has_strname();
  strname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CMsgRoleInfo.strName)
}
inline void CMsgRoleInfo::set_strname(const char* value, size_t size) {
  set_has_strname();
  strname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CMsgRoleInfo.strName)
}
inline ::std::string* CMsgRoleInfo::mutable_strname() {
  set_has_strname();
  // @@protoc_insertion_point(field_mutable:CMsgRoleInfo.strName)
  return strname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CMsgRoleInfo::release_strname() {
  clear_has_strname();
  return strname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMsgRoleInfo::set_allocated_strname(::std::string* strname) {
  if (strname != NULL) {
    set_has_strname();
  } else {
    clear_has_strname();
  }
  strname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strname);
  // @@protoc_insertion_point(field_set_allocated:CMsgRoleInfo.strName)
}

// optional uint32 idRoleType = 5;
inline bool CMsgRoleInfo::has_idroletype() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void CMsgRoleInfo::set_has_idroletype() {
  _has_bits_[0] |= 0x00000010u;
}
inline void CMsgRoleInfo::clear_has_idroletype() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void CMsgRoleInfo::clear_idroletype() {
  idroletype_ = 0u;
  clear_has_idroletype();
}
inline ::google::protobuf::uint32 CMsgRoleInfo::idroletype() const {
  // @@protoc_insertion_point(field_get:CMsgRoleInfo.idRoleType)
  return idroletype_;
}
inline void CMsgRoleInfo::set_idroletype(::google::protobuf::uint32 value) {
  set_has_idroletype();
  idroletype_ = value;
  // @@protoc_insertion_point(field_set:CMsgRoleInfo.idRoleType)
}

// optional int32 nLevel = 6;
inline bool CMsgRoleInfo::has_nlevel() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void CMsgRoleInfo::set_has_nlevel() {
  _has_bits_[0] |= 0x00000020u;
}
inline void CMsgRoleInfo::clear_has_nlevel() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void CMsgRoleInfo::clear_nlevel() {
  nlevel_ = 0;
  clear_has_nlevel();
}
inline ::google::protobuf::int32 CMsgRoleInfo::nlevel() const {
  // @@protoc_insertion_point(field_get:CMsgRoleInfo.nLevel)
  return nlevel_;
}
inline void CMsgRoleInfo::set_nlevel(::google::protobuf::int32 value) {
  set_has_nlevel();
  nlevel_ = value;
  // @@protoc_insertion_point(field_set:CMsgRoleInfo.nLevel)
}

// optional int64 nExp = 7;
inline bool CMsgRoleInfo::has_nexp() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void CMsgRoleInfo::set_has_nexp() {
  _has_bits_[0] |= 0x00000040u;
}
inline void CMsgRoleInfo::clear_has_nexp() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void CMsgRoleInfo::clear_nexp() {
  nexp_ = GOOGLE_LONGLONG(0);
  clear_has_nexp();
}
inline ::google::protobuf::int64 CMsgRoleInfo::nexp() const {
  // @@protoc_insertion_point(field_get:CMsgRoleInfo.nExp)
  return nexp_;
}
inline void CMsgRoleInfo::set_nexp(::google::protobuf::int64 value) {
  set_has_nexp();
  nexp_ = value;
  // @@protoc_insertion_point(field_set:CMsgRoleInfo.nExp)
}

// optional float fPos_x = 8;
inline bool CMsgRoleInfo::has_fpos_x() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void CMsgRoleInfo::set_has_fpos_x() {
  _has_bits_[0] |= 0x00000080u;
}
inline void CMsgRoleInfo::clear_has_fpos_x() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void CMsgRoleInfo::clear_fpos_x() {
  fpos_x_ = 0;
  clear_has_fpos_x();
}
inline float CMsgRoleInfo::fpos_x() const {
  // @@protoc_insertion_point(field_get:CMsgRoleInfo.fPos_x)
  return fpos_x_;
}
inline void CMsgRoleInfo::set_fpos_x(float value) {
  set_has_fpos_x();
  fpos_x_ = value;
  // @@protoc_insertion_point(field_set:CMsgRoleInfo.fPos_x)
}

// optional float fPos_y = 9;
inline bool CMsgRoleInfo::has_fpos_y() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void CMsgRoleInfo::set_has_fpos_y() {
  _has_bits_[0] |= 0x00000100u;
}
inline void CMsgRoleInfo::clear_has_fpos_y() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void CMsgRoleInfo::clear_fpos_y() {
  fpos_y_ = 0;
  clear_has_fpos_y();
}
inline float CMsgRoleInfo::fpos_y() const {
  // @@protoc_insertion_point(field_get:CMsgRoleInfo.fPos_y)
  return fpos_y_;
}
inline void CMsgRoleInfo::set_fpos_y(float value) {
  set_has_fpos_y();
  fpos_y_ = value;
  // @@protoc_insertion_point(field_set:CMsgRoleInfo.fPos_y)
}

// optional float fPos_z = 10;
inline bool CMsgRoleInfo::has_fpos_z() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void CMsgRoleInfo::set_has_fpos_z() {
  _has_bits_[0] |= 0x00000200u;
}
inline void CMsgRoleInfo::clear_has_fpos_z() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void CMsgRoleInfo::clear_fpos_z() {
  fpos_z_ = 0;
  clear_has_fpos_z();
}
inline float CMsgRoleInfo::fpos_z() const {
  // @@protoc_insertion_point(field_get:CMsgRoleInfo.fPos_z)
  return fpos_z_;
}
inline void CMsgRoleInfo::set_fpos_z(float value) {
  set_has_fpos_z();
  fpos_z_ = value;
  // @@protoc_insertion_point(field_set:CMsgRoleInfo.fPos_z)
}

// optional int32 nLife = 11;
inline bool CMsgRoleInfo::has_nlife() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void CMsgRoleInfo::set_has_nlife() {
  _has_bits_[0] |= 0x00000400u;
}
inline void CMsgRoleInfo::clear_has_nlife() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void CMsgRoleInfo::clear_nlife() {
  nlife_ = 0;
  clear_has_nlife();
}
inline ::google::protobuf::int32 CMsgRoleInfo::nlife() const {
  // @@protoc_insertion_point(field_get:CMsgRoleInfo.nLife)
  return nlife_;
}
inline void CMsgRoleInfo::set_nlife(::google::protobuf::int32 value) {
  set_has_nlife();
  nlife_ = value;
  // @@protoc_insertion_point(field_set:CMsgRoleInfo.nLife)
}

// optional int32 nMaxLife = 12;
inline bool CMsgRoleInfo::has_nmaxlife() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void CMsgRoleInfo::set_has_nmaxlife() {
  _has_bits_[0] |= 0x00000800u;
}
inline void CMsgRoleInfo::clear_has_nmaxlife() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void CMsgRoleInfo::clear_nmaxlife() {
  nmaxlife_ = 0;
  clear_has_nmaxlife();
}
inline ::google::protobuf::int32 CMsgRoleInfo::nmaxlife() const {
  // @@protoc_insertion_point(field_get:CMsgRoleInfo.nMaxLife)
  return nmaxlife_;
}
inline void CMsgRoleInfo::set_nmaxlife(::google::protobuf::int32 value) {
  set_has_nmaxlife();
  nmaxlife_ = value;
  // @@protoc_insertion_point(field_set:CMsgRoleInfo.nMaxLife)
}

// optional int32 nMana = 13;
inline bool CMsgRoleInfo::has_nmana() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void CMsgRoleInfo::set_has_nmana() {
  _has_bits_[0] |= 0x00001000u;
}
inline void CMsgRoleInfo::clear_has_nmana() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void CMsgRoleInfo::clear_nmana() {
  nmana_ = 0;
  clear_has_nmana();
}
inline ::google::protobuf::int32 CMsgRoleInfo::nmana() const {
  // @@protoc_insertion_point(field_get:CMsgRoleInfo.nMana)
  return nmana_;
}
inline void CMsgRoleInfo::set_nmana(::google::protobuf::int32 value) {
  set_has_nmana();
  nmana_ = value;
  // @@protoc_insertion_point(field_set:CMsgRoleInfo.nMana)
}

// optional int32 nMaxMana = 14;
inline bool CMsgRoleInfo::has_nmaxmana() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void CMsgRoleInfo::set_has_nmaxmana() {
  _has_bits_[0] |= 0x00002000u;
}
inline void CMsgRoleInfo::clear_has_nmaxmana() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void CMsgRoleInfo::clear_nmaxmana() {
  nmaxmana_ = 0;
  clear_has_nmaxmana();
}
inline ::google::protobuf::int32 CMsgRoleInfo::nmaxmana() const {
  // @@protoc_insertion_point(field_get:CMsgRoleInfo.nMaxMana)
  return nmaxmana_;
}
inline void CMsgRoleInfo::set_nmaxmana(::google::protobuf::int32 value) {
  set_has_nmaxmana();
  nmaxmana_ = value;
  // @@protoc_insertion_point(field_set:CMsgRoleInfo.nMaxMana)
}

// optional uint32 idScene = 1001;
inline bool CMsgRoleInfo::has_idscene() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
inline void CMsgRoleInfo::set_has_idscene() {
  _has_bits_[0] |= 0x00004000u;
}
inline void CMsgRoleInfo::clear_has_idscene() {
  _has_bits_[0] &= ~0x00004000u;
}
inline void CMsgRoleInfo::clear_idscene() {
  idscene_ = 0u;
  clear_has_idscene();
}
inline ::google::protobuf::uint32 CMsgRoleInfo::idscene() const {
  // @@protoc_insertion_point(field_get:CMsgRoleInfo.idScene)
  return idscene_;
}
inline void CMsgRoleInfo::set_idscene(::google::protobuf::uint32 value) {
  set_has_idscene();
  idscene_ = value;
  // @@protoc_insertion_point(field_set:CMsgRoleInfo.idScene)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::MSG_ROLE_INFO_ACTION> : ::google::protobuf::internal::true_type {};

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MsgRoleInfo_2eproto__INCLUDED
