// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgRoleSelect.proto

#ifndef PROTOBUF_MsgRoleSelect_2eproto__INCLUDED
#define PROTOBUF_MsgRoleSelect_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_MsgRoleSelect_2eproto();
void protobuf_AssignDesc_MsgRoleSelect_2eproto();
void protobuf_ShutdownFile_MsgRoleSelect_2eproto();

class CRoleSummary;
class CMsgRoleSelect;

// ===================================================================

class CRoleSummary : public ::google::protobuf::MessageLite {
 public:
  CRoleSummary();
  virtual ~CRoleSummary();

  CRoleSummary(const CRoleSummary& from);

  inline CRoleSummary& operator=(const CRoleSummary& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const CRoleSummary& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const CRoleSummary* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(CRoleSummary* other);

  // implements Message ----------------------------------------------

  inline CRoleSummary* New() const { return New(NULL); }

  CRoleSummary* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const CRoleSummary& from);
  void MergeFrom(const CRoleSummary& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CRoleSummary* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 idRole = 1;
  bool has_idrole() const;
  void clear_idrole();
  static const int kIdRoleFieldNumber = 1;
  ::google::protobuf::uint64 idrole() const;
  void set_idrole(::google::protobuf::uint64 value);

  // required string szName = 2;
  bool has_szname() const;
  void clear_szname();
  static const int kSzNameFieldNumber = 2;
  const ::std::string& szname() const;
  void set_szname(const ::std::string& value);
  void set_szname(const char* value);
  void set_szname(const char* value, size_t size);
  ::std::string* mutable_szname();
  ::std::string* release_szname();
  void set_allocated_szname(::std::string* szname);

  // optional uint32 idRoleType = 3;
  bool has_idroletype() const;
  void clear_idroletype();
  static const int kIdRoleTypeFieldNumber = 3;
  ::google::protobuf::uint32 idroletype() const;
  void set_idroletype(::google::protobuf::uint32 value);

  // optional uint32 nLevel = 4;
  bool has_nlevel() const;
  void clear_nlevel();
  static const int kNLevelFieldNumber = 4;
  ::google::protobuf::uint32 nlevel() const;
  void set_nlevel(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:CRoleSummary)
 private:
  inline void set_has_idrole();
  inline void clear_has_idrole();
  inline void set_has_szname();
  inline void clear_has_szname();
  inline void set_has_idroletype();
  inline void clear_has_idroletype();
  inline void set_has_nlevel();
  inline void clear_has_nlevel();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::std::string _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 idrole_;
  ::google::protobuf::internal::ArenaStringPtr szname_;
  ::google::protobuf::uint32 idroletype_;
  ::google::protobuf::uint32 nlevel_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_MsgRoleSelect_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_MsgRoleSelect_2eproto();
  #endif
  friend void protobuf_AssignDesc_MsgRoleSelect_2eproto();
  friend void protobuf_ShutdownFile_MsgRoleSelect_2eproto();

  void InitAsDefaultInstance();
  static CRoleSummary* default_instance_;
};
// -------------------------------------------------------------------

class CMsgRoleSelect : public ::google::protobuf::MessageLite {
 public:
  CMsgRoleSelect();
  virtual ~CMsgRoleSelect();

  CMsgRoleSelect(const CMsgRoleSelect& from);

  inline CMsgRoleSelect& operator=(const CMsgRoleSelect& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const CMsgRoleSelect& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const CMsgRoleSelect* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(CMsgRoleSelect* other);

  // implements Message ----------------------------------------------

  inline CMsgRoleSelect* New() const { return New(NULL); }

  CMsgRoleSelect* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const CMsgRoleSelect& from);
  void MergeFrom(const CMsgRoleSelect& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CMsgRoleSelect* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 idRoleSelected = 1;
  bool has_idroleselected() const;
  void clear_idroleselected();
  static const int kIdRoleSelectedFieldNumber = 1;
  ::google::protobuf::uint64 idroleselected() const;
  void set_idroleselected(::google::protobuf::uint64 value);

  // repeated .CRoleSummary roles = 2;
  int roles_size() const;
  void clear_roles();
  static const int kRolesFieldNumber = 2;
  const ::CRoleSummary& roles(int index) const;
  ::CRoleSummary* mutable_roles(int index);
  ::CRoleSummary* add_roles();
  const ::google::protobuf::RepeatedPtrField< ::CRoleSummary >&
      roles() const;
  ::google::protobuf::RepeatedPtrField< ::CRoleSummary >*
      mutable_roles();

  // @@protoc_insertion_point(class_scope:CMsgRoleSelect)
 private:
  inline void set_has_idroleselected();
  inline void clear_has_idroleselected();

  ::std::string _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 idroleselected_;
  ::google::protobuf::RepeatedPtrField< ::CRoleSummary > roles_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_MsgRoleSelect_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_MsgRoleSelect_2eproto();
  #endif
  friend void protobuf_AssignDesc_MsgRoleSelect_2eproto();
  friend void protobuf_ShutdownFile_MsgRoleSelect_2eproto();

  void InitAsDefaultInstance();
  static CMsgRoleSelect* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CRoleSummary

// required uint64 idRole = 1;
inline bool CRoleSummary::has_idrole() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CRoleSummary::set_has_idrole() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CRoleSummary::clear_has_idrole() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CRoleSummary::clear_idrole() {
  idrole_ = GOOGLE_ULONGLONG(0);
  clear_has_idrole();
}
inline ::google::protobuf::uint64 CRoleSummary::idrole() const {
  // @@protoc_insertion_point(field_get:CRoleSummary.idRole)
  return idrole_;
}
inline void CRoleSummary::set_idrole(::google::protobuf::uint64 value) {
  set_has_idrole();
  idrole_ = value;
  // @@protoc_insertion_point(field_set:CRoleSummary.idRole)
}

// required string szName = 2;
inline bool CRoleSummary::has_szname() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CRoleSummary::set_has_szname() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CRoleSummary::clear_has_szname() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CRoleSummary::clear_szname() {
  szname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_szname();
}
inline const ::std::string& CRoleSummary::szname() const {
  // @@protoc_insertion_point(field_get:CRoleSummary.szName)
  return szname_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CRoleSummary::set_szname(const ::std::string& value) {
  set_has_szname();
  szname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CRoleSummary.szName)
}
inline void CRoleSummary::set_szname(const char* value) {
  set_has_szname();
  szname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CRoleSummary.szName)
}
inline void CRoleSummary::set_szname(const char* value, size_t size) {
  set_has_szname();
  szname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CRoleSummary.szName)
}
inline ::std::string* CRoleSummary::mutable_szname() {
  set_has_szname();
  // @@protoc_insertion_point(field_mutable:CRoleSummary.szName)
  return szname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CRoleSummary::release_szname() {
  clear_has_szname();
  return szname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CRoleSummary::set_allocated_szname(::std::string* szname) {
  if (szname != NULL) {
    set_has_szname();
  } else {
    clear_has_szname();
  }
  szname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), szname);
  // @@protoc_insertion_point(field_set_allocated:CRoleSummary.szName)
}

// optional uint32 idRoleType = 3;
inline bool CRoleSummary::has_idroletype() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CRoleSummary::set_has_idroletype() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CRoleSummary::clear_has_idroletype() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CRoleSummary::clear_idroletype() {
  idroletype_ = 0u;
  clear_has_idroletype();
}
inline ::google::protobuf::uint32 CRoleSummary::idroletype() const {
  // @@protoc_insertion_point(field_get:CRoleSummary.idRoleType)
  return idroletype_;
}
inline void CRoleSummary::set_idroletype(::google::protobuf::uint32 value) {
  set_has_idroletype();
  idroletype_ = value;
  // @@protoc_insertion_point(field_set:CRoleSummary.idRoleType)
}

// optional uint32 nLevel = 4;
inline bool CRoleSummary::has_nlevel() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CRoleSummary::set_has_nlevel() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CRoleSummary::clear_has_nlevel() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CRoleSummary::clear_nlevel() {
  nlevel_ = 0u;
  clear_has_nlevel();
}
inline ::google::protobuf::uint32 CRoleSummary::nlevel() const {
  // @@protoc_insertion_point(field_get:CRoleSummary.nLevel)
  return nlevel_;
}
inline void CRoleSummary::set_nlevel(::google::protobuf::uint32 value) {
  set_has_nlevel();
  nlevel_ = value;
  // @@protoc_insertion_point(field_set:CRoleSummary.nLevel)
}

// -------------------------------------------------------------------

// CMsgRoleSelect

// optional uint64 idRoleSelected = 1;
inline bool CMsgRoleSelect::has_idroleselected() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CMsgRoleSelect::set_has_idroleselected() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CMsgRoleSelect::clear_has_idroleselected() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CMsgRoleSelect::clear_idroleselected() {
  idroleselected_ = GOOGLE_ULONGLONG(0);
  clear_has_idroleselected();
}
inline ::google::protobuf::uint64 CMsgRoleSelect::idroleselected() const {
  // @@protoc_insertion_point(field_get:CMsgRoleSelect.idRoleSelected)
  return idroleselected_;
}
inline void CMsgRoleSelect::set_idroleselected(::google::protobuf::uint64 value) {
  set_has_idroleselected();
  idroleselected_ = value;
  // @@protoc_insertion_point(field_set:CMsgRoleSelect.idRoleSelected)
}

// repeated .CRoleSummary roles = 2;
inline int CMsgRoleSelect::roles_size() const {
  return roles_.size();
}
inline void CMsgRoleSelect::clear_roles() {
  roles_.Clear();
}
inline const ::CRoleSummary& CMsgRoleSelect::roles(int index) const {
  // @@protoc_insertion_point(field_get:CMsgRoleSelect.roles)
  return roles_.Get(index);
}
inline ::CRoleSummary* CMsgRoleSelect::mutable_roles(int index) {
  // @@protoc_insertion_point(field_mutable:CMsgRoleSelect.roles)
  return roles_.Mutable(index);
}
inline ::CRoleSummary* CMsgRoleSelect::add_roles() {
  // @@protoc_insertion_point(field_add:CMsgRoleSelect.roles)
  return roles_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CRoleSummary >&
CMsgRoleSelect::roles() const {
  // @@protoc_insertion_point(field_list:CMsgRoleSelect.roles)
  return roles_;
}
inline ::google::protobuf::RepeatedPtrField< ::CRoleSummary >*
CMsgRoleSelect::mutable_roles() {
  // @@protoc_insertion_point(field_mutable_list:CMsgRoleSelect.roles)
  return &roles_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MsgRoleSelect_2eproto__INCLUDED
